#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KAS.Trukman.Droid.Resource", IsApplication=true)]

namespace KAS.Trukman.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::KAS.Trukman.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int appbutton_textcolor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int appentry_textcolor = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appboxview = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int appbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int appbutton_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int appbutton_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appbutton_left_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int appbutton_left_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int appbutton_left_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int appbutton_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int appbutton_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int appbutton_right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int appbutton_right_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int appbutton_right_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int appbutton_right_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int appentry = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int applabel = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int background_menu = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int camera = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int clock = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dislike = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int fuel = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int fuel_received = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int fuel_requested = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int gps_off = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int gps_off_warning = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int gps_on = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int home = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int home_map = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int left = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int like = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int location = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int lumper = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int lumper_received = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int lumper_requested = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int mail = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int map = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int menu = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int right = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int time = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
